In [1]:
import torch
import torch.utils.data.dataloader as dataloader
import torchvision.transforms as transforms

In [2]:
# Basic tensor operations in PyTorch
x = torch.arange(12)
print(x)
print(x.shape)
x = x.reshape(3, 4)
print(x.shape)
print(x)
x = torch.zeros(3, 4)
print(x)
# operators
u = torch.tensor([1, 2, 3])
v = torch.tensor([4, 5, 6])
print(u+v)
print(u-v)
print(u*v)
print(u/v)
print(u**v)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
torch.Size([3, 4])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])
tensor([  1,  32, 729])


In [3]:
print(u+v)

tensor([5, 7, 9])


In [1]:
import os

In [3]:
os.makedirs(os.path.join('..','data'),exist_ok=True)

In [4]:
data_file = os.path.join('..', 'data', 'house_tiny.csv')

In [5]:
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [7]:
import pandas as pd

In [8]:
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [20]:
inputs, outputs = data.iloc[:,0:2], data.iloc[:,2]
# 对数值列用均值填充
inputs['NumRooms'] = inputs['NumRooms'].fillna(inputs['NumRooms'].mean())

# 对分类列用众数填充
inputs['Alley'] = inputs['Alley'].fillna(inputs['Alley'].mode()[0])
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0  Pave
2       4.0  Pave
3       3.0  Pave


In [21]:
%matplotlib inline


ModuleNotFoundError: No module named 'd2l'